# Generated by Django 5.1.5 on 2025-01-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='table_number',
            field=models.PositiveIntegerField(unique=True, verbose_name='Номер стола'),
        ),
    ]
